name: Build & Release
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
env:
  ARTIFACT_NAME: smgr
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'
          check-latest: true
          cache-dependency-path: smgr/go.sum
      - run: cd src; go test ./...
  build:
    needs: [tests]
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.build_number.outputs.BUILD_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'
          check-latest: true
          cache-dependency-path: src/go.sum
      - name: Generate BUILD_ID
        id: build_number 
        run: |
          echo "BUILD_ID=$(echo ${GITHUB_SHA} | cut -c1-7)-$(date '+%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
      - name: Create artifact
        run: cd src; go build -o ../${{ env.ARTIFACT_NAME }}-${{ steps.build_number.outputs.BUILD_ID }} ./cmd/smgr